<template>
    <div class="theme-light">
        <header>
            <button class="theme-btn" @click="toggleTheme()">🌝<span>/</span>🌚</button>
            <a href="https://www.github.com/yuxiaoy1/awesome-newsletters/" target="_blank">
                <svg class="octicon octicon-mark-github v-align-middle" height="30" viewBox="0 0 16 16" version="1.1"
                    width="30" aria-hidden="true">
                    <path fill-rule="evenodd"
                        d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.58-8-8-8z">
                    </path>
                </svg>
            </a>
        </header>
        <Content />
    </div>
</template>
<script>
export default {
    name: "Layout",
    data() {
        return {};
    },
    methods: {
        toggleTheme() {
            const div = document.querySelector("[class^='theme']");
            const themeName = div.className;
            if (themeName !== "theme-dark") {
                this.setTheme("theme-dark");
            } else if (themeName !== "theme-light") {
                this.setTheme("theme-light");
            }
        },
        setTheme(themeName) {
            let div = document.querySelector("[class^='theme']");
            div.className = themeName;
            localStorage.setItem("theme", themeName);
        },
    },
    mounted() {
        document.title = "Awesome Newsletters";
        if (localStorage.getItem("theme") === "theme-light") {
            this.setTheme("theme-light");
        } else if (localStorage.getItem("theme") === "theme-dark") {
            this.setTheme("theme-dark");
        }
    },
};
</script>
<style>
.theme-dark {
    /* --bg-color: #0f0e17; */
    --bg-color: #17181a;
    --heading-color: #fffffe;
    /* --paragraph-color: #a7a9be; */
    --paragraph-color: #ccc;
    --list-bg-color: #1f2022;
    --secondary-color: #f25f4c;
    --secondary-light-color: #f25f4c77;
}
.theme-light {
    --bg-color: #fffffe;
    --heading-color: #0f0e17;
    --paragraph-color: #0f0e17;
    --list-bg-color: #fffffe;
    --secondary-color: #f25f4c;
    --secondary-light-color: #f25f4c77;
}
body {
    padding: 0;
    margin: 0;
}
[class^="theme"] {
    background-color: var(--bg-color);
    transition: ease 0.5s;
}
header{
    display: flex;
    justify-content: flex-end;
    align-items: center;
    padding: 2rem 2rem;
}
.theme-btn {
    padding: 0 2rem;
    background-color: transparent;
    font-size: 30px;
    cursor: pointer;
    border: none;
    outline: none;
}
.theme-btn span {
    color: var(--heading-color);
}
h1 {
    /* title */
    text-align: center;
    color: var(--heading-color);
    font-size: 48px;
    margin-top: 1rem;
    margin-bottom: 4rem;
}
h1 a {
    display: none;
}
h1 img {
    display: none;
}
h1::after {
    content: "📭";
}
p {
    color: var(--paragraph-color);
    max-width: 768px;
    margin: auto;
    padding: 0 2rem 1rem 1rem;
    text-align: center;
}
p:nth-child(2) {
    /* intro paragraph */
    font-size: 20px;
    font-weight: 700;
}
p:nth-child(3) {
    /* inspired paragraph */
    display: none;
}

a {
    color: var(--secondary-color);
}
li > a {
    display: block;
    width: max-content;
    font-size: 24px;
    text-decoration: none;
    margin-bottom: 1rem;
}
a:visited,
a:hover,
a:active {
    color: var(--secondary-light-color);
}
a span {
    /* anchor icon generated by vuepress */
    display: none;
}
ul {
    list-style: none;
    padding: 0;
    max-width: 768px;
    margin: auto;
}
ul > li {
    padding: 1.5rem;
    margin: 1rem;
    color: var(--paragraph-color);
    background-color: var(--list-bg-color);
    line-height: 1.5rem;
    font-weight: 600;
    border: solid 2px #000;
    border-radius: 0.5rem;
}
h3 {
    /* contributing */
    display: none;
}
</style>