<template>
    <div class="theme-light">
        <button class="themeBtn" @click="toggleTheme()">🌝<span>/</span>🌚</button>
        <Content />
    </div>
</template>
<script>
export default {
    name: "Layout",
    data() {
        return {};
    },
    methods: {
        toggleTheme() {
            const div = document.querySelector("[class^='theme']");
            const themeName = div.className;
            if (themeName !== "theme-dark") {
                this.setTheme("theme-dark");
            } else if (themeName !== "theme-light") {
                this.setTheme("theme-light");
            }
        },
        setTheme(themeName) {
            let div = document.querySelector("[class^='theme']");
            div.className = themeName;
            localStorage.setItem("theme", themeName);
        },
    },
    mounted() {
        document.title = "Awesome Newsletters";
        if (localStorage.getItem("theme") === "theme-light") {
            this.setTheme("theme-light");
        } else if (localStorage.getItem("theme") === "theme-dark") {
            this.setTheme("theme-dark");
        }
    },
};
</script>
<style>
.theme-dark {
    /* --bg-color: #0f0e17; */
    --bg-color: #17181a;
    --heading-color: #fffffe;
    /* --paragraph-color: #a7a9be; */
    --paragraph-color: #ccc;
    --list-bg-color: #1f2022;
    --secondary-color: #f25f4c;
    --secondary-light-color: #f25f4c77;
}
.theme-light {
    --bg-color: #fffffe;
    --heading-color: #0f0e17;
    --paragraph-color: #0f0e17;
    --list-bg-color: #fffffe;
    --secondary-color: #f25f4c;
    --secondary-light-color: #f25f4c77;
}
body {
    padding: 0;
    margin: 0;
}
[class^="theme"] {
    background-color: var(--bg-color);
    transition: ease 0.5s;
}
.themeBtn {
    display: block;
    margin-left: auto;
    margin-right: 3rem;
    padding: 2rem 1rem;
    background-color: transparent;
    font-size: 30px;
    cursor: pointer;
    border: none;
    outline: none;
}
.themeBtn span{
    color: var(--heading-color);
}
h1 {
    /* title */
    text-align: center;
    color: var(--heading-color);
    font-size: 48px;
    margin-top: 1rem;
    margin-bottom: 4rem;
}
h1 a {
    display: none;
}
h1 img {
    display: none;
}
h1::after {
    content: "📭";
}
p {
    color: var(--paragraph-color);
    max-width: 768px;
    margin: auto;
    padding: 0 2rem 1rem 1rem;
    text-align: center;
}
p:nth-child(2) {
    /* intro paragraph */
    font-size: 20px;
    font-weight: 700;
}
p:nth-child(3) {
    /* inspired paragraph */
    display: none;
}

a {
    color: var(--secondary-color);
}
li > a {
    display: block;
    width: max-content;
    font-size: 24px;
    text-decoration: none;
    margin-bottom: 1rem;
}
a:visited,
a:hover,
a:active {
    color: var(--secondary-light-color);
}
a span {
    /* anchor icon generated by vuepress */
    display: none;
}
ul {
    list-style: none;
    padding: 0;
    max-width: 768px;
    margin: auto;
}
ul > li {
    padding: 1.5rem;
    margin: 1rem;
    color: var(--paragraph-color);
    background-color: var(--list-bg-color);
    line-height: 1.5rem;
    font-weight: 600;
    border: solid 2px #000;
    border-radius: 0.5rem;
}
h3 {
    /* contributing */
    display: none;
}
</style>